# Generated by Django 3.2 on 2023-07-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0002_alter_generator_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
