# Generated by Django 3.2 on 2023-08-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0003_alter_generator_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='password',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
